spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/olapu
    username: root
    password: 123456
server:
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /doc.html
logging:
  level:
    org.kushinae.olapu.api.filter: debug
    org.springframework.data.jpa: debug